- name: install ansible
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: Enable mysql
    ansible.builtin.service:
      name: mysqld
      state: present
   