- name: install ansible
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed
  - name: Enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: mysql instation documentation
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      register: mysql_info
      ignore errors: true
  - name: print the output
    ansible.builtin.debug:
      msg: mysqlinfo "{{ mysql_info }}"